// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Base.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Base.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* PBMsg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PBMsg_reflection_ = NULL;
const ::google::protobuf::Descriptor* PBPackage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PBPackage_reflection_ = NULL;
struct PBPackageOneofInstance {
  const ::PBMsg* msg_;
}* PBPackage_default_oneof_instance_ = NULL;

}  // namespace


void protobuf_AssignDesc_Base_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_Base_2eproto() {
  protobuf_AddDesc_Base_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Base.proto");
  GOOGLE_CHECK(file != NULL);
  PBMsg_descriptor_ = file->message_type(0);
  static const int PBMsg_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMsg, d_),
  };
  PBMsg_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PBMsg_descriptor_,
      PBMsg::default_instance_,
      PBMsg_offsets_,
      -1,
      -1,
      -1,
      sizeof(PBMsg),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMsg, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMsg, _is_default_instance_));
  PBPackage_descriptor_ = file->message_type(1);
  static const int PBPackage_offsets_[2] = {
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(PBPackage_default_oneof_instance_, msg_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBPackage, PBAirMessage_),
  };
  PBPackage_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PBPackage_descriptor_,
      PBPackage::default_instance_,
      PBPackage_offsets_,
      -1,
      -1,
      -1,
      PBPackage_default_oneof_instance_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBPackage, _oneof_case_[0]),
      sizeof(PBPackage),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBPackage, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBPackage, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Base_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PBMsg_descriptor_, &PBMsg::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PBPackage_descriptor_, &PBPackage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Base_2eproto() {
  delete PBMsg::default_instance_;
  delete PBMsg_reflection_;
  delete PBPackage::default_instance_;
  delete PBPackage_default_oneof_instance_;
  delete PBPackage_reflection_;
}

void protobuf_AddDesc_Base_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_Base_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\nBase.proto\"\022\n\005PBMsg\022\t\n\001d\030\001 \001(\005\"2\n\tPBPa"
    "ckage\022\025\n\003msg\030\001 \001(\0132\006.PBMsgH\000B\016\n\014PBAirMes"
    "sageb\006proto3", 92);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Base.proto", &protobuf_RegisterTypes);
  PBMsg::default_instance_ = new PBMsg();
  PBPackage::default_instance_ = new PBPackage();
  PBPackage_default_oneof_instance_ = new PBPackageOneofInstance();
  PBMsg::default_instance_->InitAsDefaultInstance();
  PBPackage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Base_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Base_2eproto {
  StaticDescriptorInitializer_Base_2eproto() {
    protobuf_AddDesc_Base_2eproto();
  }
} static_descriptor_initializer_Base_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PBMsg::kDFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PBMsg::PBMsg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PBMsg)
}

void PBMsg::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

PBMsg::PBMsg(const PBMsg& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:PBMsg)
}

void PBMsg::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  d_ = 0;
}

PBMsg::~PBMsg() {
  // @@protoc_insertion_point(destructor:PBMsg)
  SharedDtor();
}

void PBMsg::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PBMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PBMsg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PBMsg_descriptor_;
}

const PBMsg& PBMsg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Base_2eproto();
  return *default_instance_;
}

PBMsg* PBMsg::default_instance_ = NULL;

PBMsg* PBMsg::New(::google::protobuf::Arena* arena) const {
  PBMsg* n = new PBMsg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PBMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:PBMsg)
  d_ = 0;
}

bool PBMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PBMsg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 d = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &d_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PBMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PBMsg)
  return false;
#undef DO_
}

void PBMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PBMsg)
  // optional int32 d = 1;
  if (this->d() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->d(), output);
  }

  // @@protoc_insertion_point(serialize_end:PBMsg)
}

::google::protobuf::uint8* PBMsg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:PBMsg)
  // optional int32 d = 1;
  if (this->d() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->d(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:PBMsg)
  return target;
}

int PBMsg::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:PBMsg)
  int total_size = 0;

  // optional int32 d = 1;
  if (this->d() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->d());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PBMsg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PBMsg)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const PBMsg* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PBMsg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PBMsg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PBMsg)
    MergeFrom(*source);
  }
}

void PBMsg::MergeFrom(const PBMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PBMsg)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.d() != 0) {
    set_d(from.d());
  }
}

void PBMsg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PBMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PBMsg::CopyFrom(const PBMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PBMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBMsg::IsInitialized() const {

  return true;
}

void PBMsg::Swap(PBMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PBMsg::InternalSwap(PBMsg* other) {
  std::swap(d_, other->d_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PBMsg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PBMsg_descriptor_;
  metadata.reflection = PBMsg_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PBMsg

// optional int32 d = 1;
void PBMsg::clear_d() {
  d_ = 0;
}
 ::google::protobuf::int32 PBMsg::d() const {
  // @@protoc_insertion_point(field_get:PBMsg.d)
  return d_;
}
 void PBMsg::set_d(::google::protobuf::int32 value) {
  
  d_ = value;
  // @@protoc_insertion_point(field_set:PBMsg.d)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PBPackage::kMsgFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PBPackage::PBPackage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PBPackage)
}

void PBPackage::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  PBPackage_default_oneof_instance_->msg_ = const_cast< ::PBMsg*>(&::PBMsg::default_instance());
}

PBPackage::PBPackage(const PBPackage& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:PBPackage)
}

void PBPackage::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  clear_has_PBAirMessage();
}

PBPackage::~PBPackage() {
  // @@protoc_insertion_point(destructor:PBPackage)
  SharedDtor();
}

void PBPackage::SharedDtor() {
  if (has_PBAirMessage()) {
    clear_PBAirMessage();
  }
  if (this != default_instance_) {
  }
}

void PBPackage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PBPackage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PBPackage_descriptor_;
}

const PBPackage& PBPackage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Base_2eproto();
  return *default_instance_;
}

PBPackage* PBPackage::default_instance_ = NULL;

PBPackage* PBPackage::New(::google::protobuf::Arena* arena) const {
  PBPackage* n = new PBPackage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PBPackage::clear_PBAirMessage() {
// @@protoc_insertion_point(one_of_clear_start:PBPackage)
  switch(PBAirMessage_case()) {
    case kMsg: {
      delete PBAirMessage_.msg_;
      break;
    }
    case PBAIRMESSAGE_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = PBAIRMESSAGE_NOT_SET;
}


void PBPackage::Clear() {
// @@protoc_insertion_point(message_clear_start:PBPackage)
  clear_PBAirMessage();
}

bool PBPackage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PBPackage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .PBMsg msg = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_msg()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PBPackage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PBPackage)
  return false;
#undef DO_
}

void PBPackage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PBPackage)
  // optional .PBMsg msg = 1;
  if (has_msg()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *PBAirMessage_.msg_, output);
  }

  // @@protoc_insertion_point(serialize_end:PBPackage)
}

::google::protobuf::uint8* PBPackage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:PBPackage)
  // optional .PBMsg msg = 1;
  if (has_msg()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *PBAirMessage_.msg_, false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:PBPackage)
  return target;
}

int PBPackage::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:PBPackage)
  int total_size = 0;

  switch (PBAirMessage_case()) {
    // optional .PBMsg msg = 1;
    case kMsg: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *PBAirMessage_.msg_);
      break;
    }
    case PBAIRMESSAGE_NOT_SET: {
      break;
    }
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PBPackage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PBPackage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const PBPackage* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PBPackage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PBPackage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PBPackage)
    MergeFrom(*source);
  }
}

void PBPackage::MergeFrom(const PBPackage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PBPackage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  switch (from.PBAirMessage_case()) {
    case kMsg: {
      mutable_msg()->::PBMsg::MergeFrom(from.msg());
      break;
    }
    case PBAIRMESSAGE_NOT_SET: {
      break;
    }
  }
}

void PBPackage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PBPackage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PBPackage::CopyFrom(const PBPackage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PBPackage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBPackage::IsInitialized() const {

  return true;
}

void PBPackage::Swap(PBPackage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PBPackage::InternalSwap(PBPackage* other) {
  std::swap(PBAirMessage_, other->PBAirMessage_);
  std::swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PBPackage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PBPackage_descriptor_;
  metadata.reflection = PBPackage_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PBPackage

// optional .PBMsg msg = 1;
bool PBPackage::has_msg() const {
  return PBAirMessage_case() == kMsg;
}
void PBPackage::set_has_msg() {
  _oneof_case_[0] = kMsg;
}
void PBPackage::clear_msg() {
  if (has_msg()) {
    delete PBAirMessage_.msg_;
    clear_has_PBAirMessage();
  }
}
 const ::PBMsg& PBPackage::msg() const {
  // @@protoc_insertion_point(field_get:PBPackage.msg)
  return has_msg()
      ? *PBAirMessage_.msg_
      : ::PBMsg::default_instance();
}
::PBMsg* PBPackage::mutable_msg() {
  if (!has_msg()) {
    clear_PBAirMessage();
    set_has_msg();
    PBAirMessage_.msg_ = new ::PBMsg;
  }
  // @@protoc_insertion_point(field_mutable:PBPackage.msg)
  return PBAirMessage_.msg_;
}
::PBMsg* PBPackage::release_msg() {
  // @@protoc_insertion_point(field_release:PBPackage.msg)
  if (has_msg()) {
    clear_has_PBAirMessage();
    ::PBMsg* temp = PBAirMessage_.msg_;
    PBAirMessage_.msg_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void PBPackage::set_allocated_msg(::PBMsg* msg) {
  clear_PBAirMessage();
  if (msg) {
    set_has_msg();
    PBAirMessage_.msg_ = msg;
  }
  // @@protoc_insertion_point(field_set_allocated:PBPackage.msg)
}

bool PBPackage::has_PBAirMessage() const {
  return PBAirMessage_case() != PBAIRMESSAGE_NOT_SET;
}
void PBPackage::clear_has_PBAirMessage() {
  _oneof_case_[0] = PBAIRMESSAGE_NOT_SET;
}
PBPackage::PBAirMessageCase PBPackage::PBAirMessage_case() const {
  return PBPackage::PBAirMessageCase(_oneof_case_[0]);
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
